#' Import Sources from a Manifest
#'
#' Reads an [att_export()] manifest, generates a data-acquisition R script,
#' and executes it. The script contains explicit [att_source()],
#' [att_download()], and [att_register()] calls — one block per source —
#' and is kept as a readable record of the import.
#'
#' Sources that already exist in the target store are included in the script
#' but skipped during execution (because [att_download()] and
#' [att_register()] refuse to overwrite existing provenance).
#'
#' @param path Path to the manifest JSON file (created by [att_export()]).
#'   Defaults to `attest-manifest.json` in the current working directory.
#' @param script Path for the generated R script. Defaults to `get-data.R`
#'   in the current working directory.
#' @param store Path to the target provenance store. Defaults to
#'   [att_store()].
#' @return The script path, invisibly.
#' @seealso [att_export()] to create a manifest.
#' @export
#' @examples
#' \dontrun{
#' att_import()
#' att_import("attest-manifest.json", script = "scripts/get-data.R")
#' }
att_import <- function(path = "attest-manifest.json",
                       script = "get-data.R",
                       store = NULL) {
  if (!file.exists(path)) {
    cli::cli_abort("Manifest not found at {.path {path}}.")
  }

  manifest <- jsonlite::read_json(path)

  if (!identical(manifest$manifest_type, "attest_manifest")) {
    cli::cli_abort(c(
      "File does not appear to be an attest manifest.",
      "i" = "Expected {.val manifest_type} to be {.val attest_manifest}."
    ))
  }

  if (is.null(store)) store <- att_store()

  sources <- manifest$sources %||% list()

  if (length(sources) == 0) {
    cli::cli_alert_info("Manifest contains no sources.")
    return(invisible(script))
  }

  # Generate the script
  script_lines <- generate_script(sources, store)
  writeLines(script_lines, script)
  cli::cli_alert_success("Generated {.path {script}}")

  # Execute the script
  cli::cli_alert_info(
    "Acquiring {length(sources)} source{?s} from manifest..."
  )

  n_ok <- 0L
  n_skip <- 0L
  n_fail <- 0L

  for (entry in sources) {
    result <- execute_source_entry(entry, store)
    if (result == "ok") {
      n_ok <- n_ok + 1L
    } else if (result == "skipped") {
      n_skip <- n_skip + 1L
    } else {
      n_fail <- n_fail + 1L
    }
  }

  cli::cli_text("")
  cli::cli_rule("Import complete")
  if (n_ok > 0) cli::cli_alert_success("{n_ok} source{?s} acquired")
  if (n_skip > 0) {
    cli::cli_alert_info("{n_skip} source{?s} skipped (already in store)")
  }
  if (n_fail > 0) cli::cli_alert_danger("{n_fail} source{?s} failed")

  invisible(script)
}


#' Generate an R script from manifest entries
#' @noRd
generate_script <- function(sources, store) {
  lines <- character(0)
  lines <- c(
    "# Data acquisition script",
    paste0("# Generated by attest on ", timestamp_now()),
    "",
    "library(attest)",
    ""
  )

  for (entry in sources) {
    lines <- c(lines, generate_source_block(entry), "")
  }

  lines
}


#' Generate an att_source() + att_download()/att_register() block
#' @noRd
generate_source_block <- function(entry) {
  origin <- entry$origin %||% "remote"
  meta <- entry$metadata %||% list()

  # Build att_source() arguments
  args <- list()
  args[["name"]] <- deparse(entry$name)

  if (!is.null(entry$landing_url) && length(entry$landing_url) > 0) {
    args[["landing_url"]] <- deparse(entry$landing_url)
  }

  if (origin %in% c("remote", "link")) {
    if (!is.null(entry$data_urls)) {
      args[["data_urls"]] <- deparse_named_vector(entry$data_urls)
    }
    if (!is.null(entry$metadata_urls)) {
      args[["metadata_urls"]] <- deparse_named_vector(entry$metadata_urls)
    }
  } else {
    if (!is.null(entry$data_paths)) {
      args[["data_paths"]] <- deparse_named_vector(entry$data_paths)
    }
    if (!is.null(entry$metadata_paths)) {
      args[["metadata_paths"]] <- deparse_named_vector(entry$metadata_paths)
    }
  }

  # Metadata fields
  for (field in c("title", "publisher", "year", "author",
                   "format", "description")) {
    val <- meta[[field]]
    if (!is.null(val) && length(val) > 0) {
      args[[field]] <- deparse(val)
    }
  }

  # Format the att_source() call
  arg_strings <- paste0("  ", names(args), " = ", args)
  source_call <- c(
    "src <- att_source(",
    paste0(arg_strings, collapse = ",\n"),
    ")"
  )

  # Format the acquisition call
  if (origin == "link") {
    acquire_call <- "att_link(src)"
  } else if (origin == "remote") {
    if (!is.null(entry$classify)) {
      classify_str <- deparse_classify(entry$classify)
      acquire_call <- paste0("att_download(src, classify = ", classify_str, ")")
    } else {
      acquire_call <- "att_download(src)"
    }
  } else {
    if (!is.null(entry$classify)) {
      classify_str <- deparse_classify(entry$classify)
      acquire_call <- paste0("att_register(src, classify = ", classify_str, ")")
    } else {
      acquire_call <- "att_register(src)"
    }
  }

  c(source_call, acquire_call)
}


#' Deparse a named list from the manifest into an R named character vector
#' @noRd
deparse_named_vector <- function(x) {
  nms <- names(x)
  vals <- vapply(x, as.character, character(1))
  entries <- paste0(deparse(nms), " = ", deparse(vals))

  if (length(vals) == 1) {
    paste0("c(", nms, " = ", deparse(vals), ")")
  } else {
    inner <- paste0("  ", nms, " = ", vapply(vals, deparse, character(1)))
    paste0("c(\n", paste0(inner, collapse = ",\n"), "\n)")
  }
}


#' Deparse a classify list into R code
#' @noRd
deparse_classify <- function(x) {
  parts <- character(0)
  for (role in c("data", "metadata", "ignore")) {
    if (!is.null(x[[role]])) {
      exts <- vapply(x[[role]], as.character, character(1))
      parts <- c(parts, paste0(role, " = ", deparse(exts)))
    }
  }
  paste0("list(", paste(parts, collapse = ", "), ")")
}


#' Execute a single source entry from the manifest
#' @noRd
execute_source_entry <- function(entry, store) {
  name <- entry$name
  origin <- entry$origin %||% "remote"
  meta <- entry$metadata %||% list()

  # Check if already exists
  dir_name <- gsub("[^a-zA-Z0-9_-]", "-", name)
  existing_prov <- file.path(store, dir_name, "_attest", "provenance.json")

  if (file.exists(existing_prov)) {
    cli::cli_alert_info("Skipping {.val {name}}: already exists in store")
    return("skipped")
  }

  if (origin == "link") {
    data_urls <- unlist_manifest(entry$data_urls)
    metadata_urls <- unlist_manifest(entry$metadata_urls)

    src <- att_source(
      name = name,
      landing_url = entry$landing_url,
      data_urls = data_urls,
      metadata_urls = metadata_urls,
      title = meta$title,
      publisher = meta$publisher,
      year = meta$year,
      author = meta$author,
      format = meta$format,
      description = meta$description
    )

    tryCatch(
      {
        att_link(src, store = store)
        "ok"
      },
      error = function(e) {
        cli::cli_alert_danger(
          "Failed to link {.val {name}}: {conditionMessage(e)}"
        )
        "failed"
      }
    )
  } else if (origin == "remote") {
    data_urls <- unlist_manifest(entry$data_urls)
    metadata_urls <- unlist_manifest(entry$metadata_urls)
    classify <- unlist_classify(entry$classify)

    src <- att_source(
      name = name,
      landing_url = entry$landing_url,
      data_urls = data_urls,
      metadata_urls = metadata_urls,
      title = meta$title,
      publisher = meta$publisher,
      year = meta$year,
      author = meta$author,
      format = meta$format,
      description = meta$description
    )

    tryCatch(
      {
        att_download(src, store = store, classify = classify)
        "ok"
      },
      error = function(e) {
        cli::cli_alert_danger(
          "Failed to download {.val {name}}: {conditionMessage(e)}"
        )
        "failed"
      }
    )
  } else {
    data_paths <- unlist_manifest(entry$data_paths)
    metadata_paths <- unlist_manifest(entry$metadata_paths)

    all_paths <- c(data_paths, metadata_paths)
    missing <- all_paths[!file.exists(all_paths)]

    if (length(missing) > 0) {
      cli::cli_alert_warning(
        "Skipping {.val {name}}: {length(missing)} file{?s} not found"
      )
      for (m in missing) {
        cli::cli_alert_danger("  {.path {m}}")
      }
      return("failed")
    }

    src <- att_source(
      name = name,
      landing_url = entry$landing_url,
      data_paths = data_paths,
      metadata_paths = metadata_paths,
      title = meta$title,
      publisher = meta$publisher,
      year = meta$year,
      author = meta$author,
      format = meta$format,
      description = meta$description
    )

    classify <- unlist_classify(entry$classify)

    tryCatch(
      {
        att_register(src, store = store, classify = classify)
        "ok"
      },
      error = function(e) {
        cli::cli_alert_danger(
          "Failed to register {.val {name}}: {conditionMessage(e)}"
        )
        "failed"
      }
    )
  }
}


#' Convert a JSON named list to a named character vector
#' @noRd
unlist_manifest <- function(x) {
  if (is.null(x) || length(x) == 0) return(NULL)
  vals <- vapply(x, function(v) as.character(v), character(1))
  nms <- names(x)
  stats::setNames(vals, nms)
}


#' Convert a JSON classify object to the list format expected by
#' att_download()
#' @noRd
unlist_classify <- function(x) {
  if (is.null(x)) return(NULL)
  result <- list()
  for (role in c("data", "metadata", "ignore")) {
    if (!is.null(x[[role]])) {
      result[[role]] <- vapply(x[[role]], as.character, character(1))
    }
  }
  if (length(result) == 0) return(NULL)
  result
}
